import { Tajawal } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar/Navbar";
import Footer from "./(components)/Footer/Footer";

const inter = Tajawal({ subsets: ["arabic"], weight: ["200", "300", "500", "700", "800", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create  app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
